### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by yriveiro** [ipselon/material-ui-prepack#9]
I have this error when I try to run structor in this repository.

```
workspace (master) $ structor -p 8080
module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/structor/server/structor/middlewareCompilerManager.js:1:1783)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by ipselon** [comment]
@yriveiro material-ui-prepack is not compatible with Structor v 2.0.0. Take a loot at Structor's readme. Sorry, for inconvenience.

**Comment by yriveiro** [comment]
:(
